/* eslint-disable no-undef */
'use strict';

// tests for graphql
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('graphql', '/src/handler.js', 'handler');

let defaultEvent = {
  httpMethod: 'POST',
  path: '/dev/graphql',
  body: {},
  headers: {
    'Content-Type': 'application/json',
  },
};

describe('graphql', () => {
  before(done => {
    done();
  });

  describe('.order', () => {
    it('endpoint works', async () => {
      const event = {
        ...defaultEvent,
        body:
          '{"query":"query {\\n  getOrder {id, customer, total}\\n    }","variables":{},"operationName":null}',
      };

      const response = await wrapped.run(event);
      expect(response).to.not.be.empty;
      expect(response.statusCode).to.equal(200);
    });
  });

  describe('.product', () => {
    it('endpoint works', async () => {
      const event = {
        ...defaultEvent,
        body:
          '{"query":"query {\\n  getProduct {id, name, photo, price, stock}\\n    }","variables":{},"operationName":null}',
      };

      const response = await wrapped.run(event);
      expect(response).to.not.be.empty;
      expect(response.statusCode).to.equal(200);
    });
  });
});
